### PR TITLE
Turned on 'download' for Mutation Vector dataset columns

### PR DESCRIPTION
**Pull request by achang28**
1) Formatted mutation vector data into their respective categories, and made them available for file download.
2) Accounted for all sample scenarios: withMutations, noMutations, blankMutations.

Issue https://github.com/ucscXena/ucsc-xena-client/issues/52

### CODE REVIEW

**Comment by achang28** [comment]
Will be sure to remove comments from (new) lines 188 thru 196, if this PR looks good.

**Comment by acthp** [comment]
I suspect this can be simpler. ```index.bySample``` already has the rows grouped by sample. The group is empty if there are no mutations. The group doesn't exist (```undefined```) if we have no data. (Say "no data", not "blank mutations".) So the return can be in the shape```_.map(samples, s => makeRow(fields, bySample[s])```, where ```makeRow``` dispatches three ways: has mutations, has no mutations, has no data.

I'm not sure what the ```_.intersection``` call is for. The fields should be the same for all rows. Extracting the fields is a map of ```fields``` over the rows, ```_.map(fields, f => row[f])``` or over a function returning a constant ('no mutation', or undefined). Multiple rows for a sample can be concatenated after the map by using ```_.flatmap``` instead of  ```_.map```.

**Comment by achang28** [comment]
I think I see what you're saying -- what you describe is definitely cleaner, especially given the idea that most of the work should be done within `makeRow`.  Didn't know about `_.flatmap` earlier; just saw it under **underscore_ext.js**; but am eager to use it.

`_.intersection` was used to determine the fields that were only applicable for "no data"-samples, so that when creating rows for these samples, only the sample IDs/Codes would be provided (no falsey values such as undefined or null).  In short, I should have simply used the "Sample" field, and avoid this `_.intersection` operation.  Regardless, I will lean mapping over all fields and return the appropriate value ("no mutation", undefined, or the actual value provided by the sample row)

**Comment by achang28** [comment]
Q(uestion):  Are (would there be) instances where `data.ref.rows` is empty or null, yet `index.bySample` has groups (only empty arrays)?  Essentially all samples with 'No Mutations' or no data.  Since there wouldn't be any fields to reference, we still need to ensure each sample row is populated with `No Mutation`...

**Comment by acthp** [comment]
Yes, there will be genes for which no samples in the dataset have mutations. In that case ```rows``` is empty, but ```index.bySample``` has empty arrays for every sample in the dataset. Providing sample & result columns in this case is good enough.

**Comment by acthp** [comment]
Looks much better. Can you replace the ```new Array``` calls with array literals, to say in the style of the rest of the code?

**Comment by achang28** [comment]
Cool -- changing them now.

**Pull request merged**
