### PR TITLE
Converted Welcome.js to ES6 Class syntax and Fixed Issue #183

### PR DESCRIPTION
**Pull request by pulkitkkr**
Converted Welcome.js View to ES6 Classes syntax, Looking forward to converting all other Views to ES6 Classes and stateless syntax (depending on requirements of the module).

### CODE REVIEW

**Comment by acthp** [comment]
This looks great! There are some minor lint errors. ghooks should have installed a pre-commit hook that runs "npm run lint". Can you manually run "npm run lint", and fix the issues? Your editor might have an eslint plugin that will show the errors when to save a file.

Check your .git/hooks/pre-commit to see if it was written correctly on install. It should start

```javascript
#!/usr/bin/env node
'use strict';

// Generated by ghooks. Do not edit this file.
```

What OS do you use for development? The hook may not work on Windows. I'm not sure.

I just enabled es7 class properties in the build, so we can do the handler binding in the class declaration with arrow functions, like

```javascript
dismissWelcome = () => {
```

instead of ```this.dismissWelcome.bind(this)```.

I think this will be less verbose, in the components that have more handlers.

Also, be aware that there are a couple mixins in the code, in ```js/react-utils.js```, that will have to be revisited when converting to es6 classes.

**Comment by pulkitkkr** [comment]
@acthp Just committed to fork/master with Eslint configuration in mind. Will start updating other View files too further, I wish to contribute to the repository, is there any official slack channel?

**Comment by acthp** [comment]
@pulkitkkr Lint fixes look good! Can you re-submit without the #183 fix? It should be a separate PR.

Re: #183, the build fails due to missing package ie-version. Needs to be added to package.json. Also, I think we will need to cover a few more details. I'll update that issue.

**Comment by pulkitkkr** [comment]
@acthp It can be merged now, the head reset hard at "Updated using Lint configuration" commit

**Pull request merged**
