### PR TITLE
For issue #122: filter out non-coding mutations for MUPIT

### PR DESCRIPTION
**Pull request by krepecka**
For issue #122.

As far as I was able to test - code works fine. But I'm still not quite sure if using `_.values(this.props.data.refGene)[0]` is stable enough and will work in all cases. Comments are highly appreciated.

### CODE REVIEW

**Comment by acthp** [comment]
Yes, that's a data modeling flaw on my part. The intent was to handle cases where multiple genes were in view on the column. An example might be gene fusions. But we haven't developed a gene fusion display. Then it was complicated by the ```field``` being very polymorphic: we have genes, probes, probes in a gene, gene sets, signatures, chrom ranges. You want an idiom like ```refGene[field[0]]```, but currently that doesn't work. So, ```values```. I'll be looking at refactoring this state in the next couple months.

Code looks good, though I recommend using ```forEach``` vs. ```map``` to convey intent when you want to run side effects vs. return a data structure. It's also faster when the lengths gets large, because you're not building a data structure only to discard it.

We will test to verify function, probably Monday, and commit if all looks good.

Thanks!

**Comment by krepecka** [comment]
Oh yes, using `forEach` instead of `map` here makes a lot of sense, especially, as you said, because array gets built just to be discarded afterwards. Learnt something :)

Thank you!

**Comment by acthp** [comment]
@krepecka We've realized, in testing, that there are two additional constraints that we forgot to consider. One is the zoom: we want to only include mutations that are in the current zoom. Second is the cds:

https://en.wikipedia.org/wiki/Coding_region

I'll probably get the biology wrong, but as I understand it, during transcription the gene is copied to RNA, then the introns are sliced out (leaving the exons), then the coding region is translated to protein.

The effect of the cds is that some exons may be outside the cds, and some exons may span the cds boundary. So prior to doing ```forEach``` on the exons, they must be filtered and clipped: filtered if they're outside the cds, and clipped if they span a cds boundary. The cds start and end are in the refGene object. There is a similar computation here:

https://github.com/ucscXena/ucsc-xena-client/blob/master/js/exonLayout.js#L22

A complication is that the stats from ```SNVPvalue``` must include all the coding mutations, so the filter by zoom must happen after that.

So, the final algorithm is something like

- clip/filter exons on cds boundaries
- call ```matches``` on the clipped/filtered exons to get all coding mutations
- pass to ```SNVPvalue``` to compute stats
- filter by ```props.column.xzoom``` if it is not undefined

Can you make these changes?

**Comment by jingchunzhu** [comment]
@acthp biology in the above comment is correct.

**Comment by krepecka** [comment]
I will take a look at it tomorrow and update pull request (or ask questions if something's unclear). But given the detailed explanation, I should be able make the changes.

**Comment by krepecka** [comment]
@acthp pull request updated. 
Considered using `reduce` in line [318,](https://github.com/ucscXena/ucsc-xena-client/pull/205/commits/64f9bf578f89139e84716bbe080b9c1ae276e640?diff=unified#diff-6311411810af26be48dfcd7b0437ba97R319) but stayed with `filter` + `map` for readability (and I think `reduce` does not give much of a performance boost).

**Comment by acthp** [comment]
@krepecka Functionality is looking good. It might be good to avoid calling ```parseInt``` twice, and reduce lookups by putting ```xzoom``` in a var. These are not big issues & can be deferred.

Can you rebase to squash to a single commit?

**Pull request merged**
