### PR TITLE
Fix geneset popup 1

### PR DESCRIPTION
**Pull request by nathandunn**
- [x] fix headers 
- [x] retest flow

### CODE REVIEW

**Comment by nathandunn** [comment]
image

**Comment by nathandunn** [comment]
vs:

**Comment by maryjgoldman** [comment]
Looks better! I'm wondering if 
1. we can have 'Differential Geneset Visualization' be the same color as 'Kaplan Meier'
2. remove the gray box, since it doesn't match any other styling we have
3. can we style the text more like the boxes from the Xena intro? (see below) For instance, use horizontal lines as dividers, the small black text as text in general, etc.
Screen Shot 2020-06-17 at 11 44 25 AM

Also, where is the cancel button? Perhaps it is just scrolled out of frame.

**Comment by nathandunn** [comment]
@maryjgoldman  I think we can do most of those.  there is no `cancel` button though.  Just the close box similar to the KM chart.

**Comment by nathandunn** [comment]
I should be able to integrate the rest of those changes, though.  I was wondering about the boxes as well.

**Comment by nathandunn** [comment]
- [ ] rest solution

**Comment by nathandunn** [comment]
@maryjgoldman  It looks like this now:

image

. . . 

Fixing the last page now

**Comment by nathandunn** [comment]
lsat page of the wizard:

**Pull request merged**
