### PR TITLE
Es6 Conversion for Application Page and issue #200 & issue #93 resolved

### PR DESCRIPTION
**Pull request by pulkitkkr**
Raising this pull request, as I wish to work on IE Warning issue

### CODE REVIEW

**Comment by acthp** [comment]
Thanks! I tested the merge, but hit a few issues:

1) Fails integration test.

The integration tests are relatively new, so running them is not entirely automated. I will try to get the details added to the test docs, here:
https://github.com/ucscXena/ucsc-xena-client/blob/master/docs/integration-testing.md

Roughly, you run the cypress heatmap-spec with CYPRESS_RECORD=true to build a local cache of network responses, then run the generative page-loading suite from node. I'll put the exact commands in the doc, when I have a moment.

The failure occurs when loading /hub/, and appears to be due to an incorrect ```import``` in PageContainer.js.

2) Lint error in PageContainer.js

3) Lots of whitespace in the second diff.

4) We don't want to drop the commented-out code in Application.js, as it's useful for performance testing.

5) I'm not sure why the constructor() method is required in Application. I found this stackoverflow answer re: calling super():

https://stackoverflow.com/questions/30571875/whats-the-difference-between-super-and-superprops-in-react-when-using-e#34995257
Is there some reason we need it?

With the whitespace, especially, it's best to discard the existing commits, and create clean ones, which will then require a force-push to put it on github.

**Comment by pulkitkkr** [comment]
@acthp 
1.) I have just pushed a new commit with corrected imports, please check for integration testing,
2) Lint error in PageContainer.js is removed
3) I'm unable to get what that meant exactly... can you please brief a bit more about it.
4) just added back, dropped out comments in-place
5) removed it, since PageContainer.js won't have any constructor, thus it is not required in Application.js

**Comment by acthp** [comment]
Integration tests are passing, now!

Regarding whitespace, I mean changes that are just formatting, rather than functional. For example, in Application.js, ```onFilter```, ```onFilterZoom```, ```onFilterColumn``` have be re-indented. ```render()``` has been re-indented. This makes the diffs harder to follow. It's best to avoid making unrelated formatting changes like this.

I just noticed in this file a number of default ```null``` values have been changed to empty string, including the onFilter* methods (at top of ```render()```), ```Welcome```, ```KmPlot```, and ```StateError```. Was there a problem with ```null```? I think it's better to use ```null```, especially for callbacks: a string-valued callback is odd.

Also, less critical, I don't think we need bother switching ```var``` statements to ```let``` and ```const```. I don't believe they're worth the effort. Also not worth the effort to change them back.

If you can restore the ```null```s, and remove the whitespace changes, I think we're good to merge. To avoid having a lot of noisy commits, squash them and force push. In detail

1) Restore ```null``` values that were changed
2) Restore changed whitespace.
3) Rebase to the commit before your first one, e.g. "git rebase -i c70890353a7c". You should see 2 commits from master at the top, followed by your commits. Change all your commits after the 1st one to "fixup", so they will be combined with your first commit.
4) Use "git push --force" to put the new history on github

Eliminating whitespace change is easiest if your editor has a "visible tabs" setting, and a side-by-side diff tool. Diff against c70890353a7c, and edit until the unrelated tab, space, and newline changes are gone.

If you haven't used rebase before to rewrite history, you can find a lot of articles online.

btw, the whitespace formatting in our repo has some inconsistencies. We're aware of the problem, and hopefully will have a uniform solution soon. Meanwhile, just try to avoid introducing whitespace changes outside of the lines you're editing.

**Comment by pulkitkkr** [comment]
@acthp  I have rebased and fixed the whitespaces, along with replacing with null

**Comment by pulkitkkr** [comment]
Also made changes to resolve issue https://github.com/ucscXena/ucsc-xena-client/issues/93

**Comment by acthp** [comment]
@pulkitkkr We really need the separate issues in separate PRs. If you have multiple fixes ready, it's easy to create additional branches off upstream/master, and issue PRs from them.

I can send details, if necessary. Briefly, add a remote for upstream, if you haven't. Create a new branch off upstream/master. cherry-pick a stand-alone fix from your master. Push the new branch. Create a new PR for the fix. After making PRs for the two unrelated issues, rebase master to remove those issues & collapse your es6 fixes to one commit. Also, there's still a lot of whitespace changes in 9f01f05. Check the diffs here, for lines that are the same except for spacing:

https://github.com/ucscXena/ucsc-xena-client/pull/198/commits/9f01f05618b4ba77765a9b0d65c223371d7e72d1

**Comment by acthp** [comment]
whitespace in Application.js is looking good, now. There are two lines with whitespace change in js/main.js, before ```_.extend```.

Fix those, and rebase to combine the changes into one commit, and I think it will be ready.

**Comment by pulkitkkr** [comment]
@acthp there was some issue after doing rebase, the history was duplicated, I have re-forked and raised a new PR https://github.com/ucscXena/ucsc-xena-client/pull/202 also, for separate PR, how am I supposed to create different branches.....

**Pull request closed without merging**
