### PR TITLE
Refactor StateError using React-toolbox issue #199

### PR DESCRIPTION
**Pull request by syt123450**
@acthp  In this PR, I refactor the "StateError" using react-toolbox. It has been tested by setting the "store.js" to trigger the "StateError" (mentioned in issue [#199](https://github.com/ucscXena/ucsc-xena-client/issues/199)). It works well in Chrome, Safari, and Firefox. If this component is ok, I will continue refactoring other bootstrap components in this way.

The screen shot of StateError is as shown below:
stateerror

PS. I add two more small features, in previous, the modal can only be closed by clicking the close button. Now I add two more ways: press "esc" on keyboard or click the overlay(shadow area), I think it may have better user experience. If you do not want these small features, I can remove it quickly.

Thanks.

### CODE REVIEW

**Comment by acthp** [comment]
@syt123450 This looks pretty good! A few issues:

1) The rest of the project is indented with hard tabs. In the diff it's reformatted with spaces. Back out unrelated whitespace changes in diffs. To avoid future problems, change your editor to use hard tabs for this project. It's easier to avoid problems if your editor has a "visible whitespace" setting, so you can see tabs vs. spaces. It's especially useful if there's a side-by-side diff mode, because then you can see if you've introduced any whitespace changes.

2) material icons is already in the build. The close button should be the standard icon, not the letter "x". You can see an example in views/Welcome.js, and views/Welcome.module.css.

3) The css classes in the diff are very general, and unqualified. Remember that css is a global name space, so common words like "close" have a high chance of aliasing with another rule. Most of the code is now converted to use local css names, via css modules. See views/Welcome.module.css, and views/Welcome.js for example. A file ending in "module.css" will be compiled with file-scoped class names, which are exposed to the javascript on import. This would be a good time to move StateError.css to a css module, though using a qualified name of some sort would also avoid future problems. That's why the original css used StateErrorContainer: it's a manual solution for what css modules does automatically.

Can you fix these issues? Thanks!

**Comment by syt123450** [comment]
@acthp Thank you for your suggestions, based on your suggestions, I did three main changes to my source code, and commit them. The changes is listed below:

1. Use hard tab to replace the space, the screen shot of code showing hard tab is as shown below: 
indent with tab

2. Change the close button to standard icon (follow welcome.js and welcome.module.css), the style of close button has been changed, the screen shot of StateError component is as shown below:
stateerror

3. Refactor the StateError.css to StateError.module.css, it has been tested and works well.

**Comment by acthp** [comment]
Looking better! Re: css classes, sorry if I wasn't clear, the suggestion was to use either a qualified name, or a css module which will qualify it automatically. You've done both, so the css classes now look like this:

```StateError-module__stateErrorDialogClose```

with the module name appearing twice. This doesn't break anything, but it really isn't necessary.

Can you remove the "stateError" prefix from the classes in StateError.module.css, and then rebase to squash the three commits into one commit?

**Comment by syt123450** [comment]
@acthp Sorry for misunderstanding your suggestion. I refactor the css class name and merge three commit into one commit this time. And the code has been test again, all function can work well as before.

**Pull request merged**
