### PR TITLE
Rebased w/ upstream dev

### PR DESCRIPTION
**Pull request by achang28**
@acthp This is more for review of where i'm at.  Still more work to do, especially with crosshair lines, and accounting for some edge cases.  Will perform "cleanup" activities once everything looks good: squash commits, whitespaces, comments, etc.

Issue https://github.com/ucscXena/ucsc-xena-client/issues/13

### CODE REVIEW

**Comment by achang28** [comment]
There is a weird issue when setting within crosshairs.css, the z-index of each crosshair line ('.CrosshairH' and '.CrosshairV').  When z-index is set, the crosshairs and tooltip section will flicker; however when not set, no flickering.  I am looking around to see what other way to bypass this issue in order to have the crosshair lines brought to the foreground.

**Comment by acthp** [comment]
Flicker with z-index is because when the crosshair is in front of the plot it's no longer 'over' the plot. It's over the crosshair. We get a mouseout event & the tooltip is closed.

**Comment by acthp** [comment]
In master branch each crosshair has class ```crosshair```, in addition to the class for their orientation. Since ```crosshair``` has ```pointer-events: none``` it does not cause a ```mouseout```.

There's also a bit of lag between the mouse & crosshair, which is distracting. One solution is to change the ```.Column``` cursor to ```none```, so the lag is not visible.

**Comment by achang28** [comment]
Thanks for the tip on removing cursor -- set this parameter earlier, but in the wrong component (Crosshair.js).  Thusfar the crosshairs work, but deviate a little bit from production in that they go beyond the bounds of the Spreadsheet.  Is this something we can "fix" later?

**Pull request merged**
