### PR TITLE
filter menu options grayed out

### PR DESCRIPTION
**Pull request by superdyzio**
fix for #223

### CODE REVIEW

**Comment by acthp** [comment]
The diff looks clean, but functionality isn't quite right. The callbacks are disabled in two cases, in Application.js:

```
!(matches < samples.length && matches > 0)
```
So with this fix, if you erase the search term the buttons don't work but also aren't grayed out. That's because ```matches === samples.length```.

Rather than duplicating this check in SampleSearch.js, it would make more sense to pass the value down in a property, like ```disabled```. At the same time, if the buttons are disabled, the callbacks in SampleSearch don't need to be set conditionally, and the closures in ```Application::render``` can be eliminated.

In detail, eliminate local vars ```onFilter```, etc., in ```Application::render```; pass ```this.onFilter```, etc., to SampleSearch instead of the vars; modify ```this.onFilter```, etc., to have no args & get their values from ```this.props```; compute ```disabled``` in ```Application:render```, and pass to SampleSearch.

Does that make sense?

**Comment by acthp** [comment]
I also recommend not using # in a branch name, since it acts as the start of a shell comment.

**Comment by superdyzio** [comment]
@acthp thanks for review, I'll look on that today. Good point with branch name, I didn't think of that. Can I rename branch without declining pr and opening new? Because I'm not so sure about it and I don't want to create new one. Can current name broke anything in f.e. builds or something?

**Comment by acthp** [comment]
It's not necessary to rename the branch.

**Comment by superdyzio** [comment]
@acthp now I see what you meant, you're right - fixed, please have a look, thanks!

**Comment by acthp** [comment]
This looks great so far, but the methods need to be updated to look up the parameters that were previously in the closures. The menu options aren't working right now, because the params are wrong. ```onFilter```, ```onFilterZoom```, ```onFilterColumn```  expect to be called with ```samples``` and ```samplesMatched```. Instead they should take them from ```this.props.state```.

Can you make that change, and rebase to squash the commits?

**Comment by superdyzio** [comment]
@acthp Should be ok now
I've asked one more question in the related issue: https://github.com/ucscXena/ucsc-xena-client/issues/223#issuecomment-374874195

**Comment by syt123450** [comment]
A simpler way is to "reset" the branch and write a new commit. Hope it can help. @superdyzio

**Comment by superdyzio** [comment]
This looks to be already fixed on master.

**Pull request closed without merging**
